#!/usr/bin/env bash
# Idempotent installer for MCP Hub on a systemd host.
#
#   sudo ./deploy/install.sh
#
# Safe to re-run: it never overwrites .env, hosts.yaml, or an existing unit
# file, and it never generates a token that already exists.
set -euo pipefail

PREFIX="${PREFIX:-/opt/mcp-hub}"
RESCUE_PREFIX="${RESCUE_PREFIX:-/opt/mcp-hub-rescue}"
SERVICE_USER="${SERVICE_USER:-mcphub}"
ENV_FILE="${ENV_FILE:-/etc/default/mcp-hub}"
UNIT_FILE="${UNIT_FILE:-/etc/systemd/system/mcp-hub.service}"
RESCUE_BIN="${RESCUE_BIN:-/usr/local/bin/mcp-hub-rescue}"
SSH_KEY="${SSH_KEY:-/home/$SERVICE_USER/.ssh/id_ed25519}"
SYSTEMCTL="${SYSTEMCTL:-systemctl}"
INSTALL_DEPENDENCIES="${INSTALL_DEPENDENCIES:-true}"
INSTALL_SSH_KEY="${INSTALL_SSH_KEY:-true}"
RELOAD_SYSTEMD="${RELOAD_SYSTEMD:-true}"

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxxx\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo $0)"
command -v "$SYSTEMCTL" >/dev/null || die "systemd is required"
command -v python3   >/dev/null || die "python3 is required"

python3 - <<'PY' || die "Python 3.11+ is required"
import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)
PY

# --- service user ------------------------------------------------------------
if id -u "$SERVICE_USER" >/dev/null 2>&1; then
  log "user $SERVICE_USER already exists"
else
  log "creating system user $SERVICE_USER"
  useradd --system --create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

# --- code --------------------------------------------------------------------
log "installing code to $PREFIX"
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$PREFIX"
for f in server.py config.py _version.py wake-host.py requirements.txt pyproject.toml README.md SECURITY.md LICENSE .env.example auth-profiles.example.json CHANGELOG.md CONTRIBUTING.md; do
  [[ -f "$SRC/$f" ]] && install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$SRC/$f" "$PREFIX/$f"
done
chmod 0750 "$PREFIX/server.py" "$PREFIX/wake-host.py"
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$PREFIX/deploy"
install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 \
  "$SRC/deploy/bw-serve-start.sh" "$PREFIX/deploy/bw-serve-start.sh"
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$PREFIX/tools"
for f in "$SRC"/tools/*.py; do
  install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$f" "$PREFIX/tools/$(basename "$f")"
done
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$PREFIX/docs"
for f in "$SRC"/docs/*.md; do
  install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$f" "$PREFIX/docs/$(basename "$f")"
done
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$PREFIX/core"
for f in "$SRC"/core/*.py; do
  install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$f" "$PREFIX/core/$(basename "$f")"
done

# Rescue is deliberately outside PREFIX and uses the system Python. A broken
# hub virtualenv or import must not make its diagnostics unavailable.
log "installing independent Rescue CLI to $RESCUE_PREFIX"
install -d -o root -g root -m 0755 "$RESCUE_PREFIX/rescue"
for f in "$SRC"/rescue/*.py; do
  install -o root -g root -m 0644 "$f" "$RESCUE_PREFIX/rescue/$(basename "$f")"
done
sed "s|/opt/mcp-hub-rescue|$RESCUE_PREFIX|g" \
  "$SRC/deploy/mcp-hub-rescue" > "$RESCUE_BIN"
chmod 0755 "$RESCUE_BIN"

# --- config templates (never overwrite) ---------------------------------------
for pair in "hosts.example.yaml:hosts.yaml" \
            "topology.example.yaml:topology.yaml" \
            "endpoints.example.yaml:endpoints.yaml"; do
  src="${pair%%:*}"; dst="${pair##*:}"
  if [[ -e "$PREFIX/$dst" ]]; then
    log "$dst already present, left untouched"
  else
    log "seeding $dst from $src"
    install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$SRC/$src" "$PREFIX/$dst"
  fi
  install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$SRC/$src" "$PREFIX/$src"
done

# --- virtualenv --------------------------------------------------------------
if [[ "$INSTALL_DEPENDENCIES" == "true" ]]; then
  if [[ -x "$PREFIX/.venv/bin/python" ]]; then
    log "virtualenv already present, updating dependencies"
  else
    log "creating virtualenv"
    sudo -u "$SERVICE_USER" python3 -m venv "$PREFIX/.venv"
  fi
  sudo -u "$SERVICE_USER" "$PREFIX/.venv/bin/pip" install --quiet --upgrade pip
  sudo -u "$SERVICE_USER" "$PREFIX/.venv/bin/pip" install --quiet -r "$PREFIX/requirements.txt"
else
  log "dependency installation skipped"
fi

# --- environment file ----------------------------------------------------------
if [[ -e "$ENV_FILE" ]]; then
  log "$ENV_FILE already present, left untouched"
else
  log "creating $ENV_FILE with generated secrets"
  secret_path="/$(openssl rand -hex 16)"
  auth_token="$(openssl rand -hex 32)"
  install -o root -g root -m 0600 /dev/null "$ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh. See .env.example for every option.
MCP_HUB_HOME=$PREFIX
MCP_BIND_ADDR=127.0.0.1
MCP_PORT=8000
MCP_SECRET_PATH=$secret_path
MCP_AUTH_TOKEN=$auth_token
MCP_READ_ONLY=true
MCP_SSH_KEY=/home/$SERVICE_USER/.ssh/id_ed25519
MCP_SECRETS_PROVIDER=env
EOF
  warn "endpoint path : $secret_path"
  warn "bearer token  : $auth_token"
  warn "Both are stored in $ENV_FILE (root, 0600). Save them in your password manager."
fi

# --- ssh key -----------------------------------------------------------------
if [[ "$INSTALL_SSH_KEY" == "true" ]]; then
  if [[ -f "$SSH_KEY" ]]; then
    log "ssh key already present"
  else
    log "generating a dedicated ssh key for $SERVICE_USER"
    install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0700 "$(dirname "$SSH_KEY")"
    sudo -u "$SERVICE_USER" ssh-keygen -t ed25519 -N "" -C "mcp-hub@$(hostname)" -f "$SSH_KEY" >/dev/null
    warn "authorise this key on your fleet:"
    cat "$SSH_KEY.pub"
  fi
else
  log "SSH key generation skipped"
fi

# --- systemd unit ------------------------------------------------------------------
if [[ -e "$UNIT_FILE" ]]; then
  log "$UNIT_FILE already present, left untouched"
else
  log "installing systemd unit"
  sed -e "s|/opt/mcp-hub|$PREFIX|g" -e "s|^User=mcphub|User=$SERVICE_USER|" \
      -e "s|^Group=mcphub|Group=$SERVICE_USER|" \
      "$SRC/deploy/mcp-hub.service.example" > "$UNIT_FILE"
  chmod 0644 "$UNIT_FILE"
fi

if [[ "$RELOAD_SYSTEMD" == "true" ]]; then
  "$SYSTEMCTL" daemon-reload
else
  log "systemd reload skipped"
fi
log "done."
echo
echo "Next:"
echo "  1. edit $PREFIX/hosts.yaml   — declare your fleet"
echo "  2. edit $ENV_FILE            — enable the integrations you want"
echo "  3. systemctl enable --now mcp-hub"
echo "  4. mcp-hub-rescue doctor     — verify the independent diagnostics"
echo
warn "MCP_READ_ONLY=true is set. Flip it to false only once you trust the setup."
