#!/usr/bin/env python3
"""Generate the complete grouped MCP tool reference without importing the hub."""
from __future__ import annotations

import argparse
import ast
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "server.py"
README = ROOT / "README.md"
OUTPUT = ROOT / "docs" / "tool-reference.md"

GROUP_ROW = re.compile(r"^\| \*\*(.+?)\*\* \| (.+) \|$", re.MULTILINE)
TOOL_NAME = re.compile(r"`([a-z][a-z0-9_]*)`")


def _is_tool(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(
        isinstance(decorator, ast.Call)
        and isinstance(decorator.func, ast.Attribute)
        and isinstance(decorator.func.value, ast.Name)
        and decorator.func.value.id == "mcp"
        and decorator.func.attr == "tool"
        for decorator in node.decorator_list
    )


def _parameter(name: str, annotation: ast.expr | None, default: ast.expr | None) -> str:
    rendered = name
    if annotation is not None:
        rendered += f": {ast.unparse(annotation)}"
    if default is not None:
        rendered += f" = {ast.unparse(default)}"
    return rendered


def _signature(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    public_name: str,
) -> str:
    args = node.args
    positional = [*args.posonlyargs, *args.args]
    defaults: list[ast.expr | None] = [None] * (
        len(positional) - len(args.defaults)
    ) + list(args.defaults)
    rendered = [
        _parameter(argument.arg, argument.annotation, default)
        for argument, default in zip(positional, defaults, strict=True)
    ]
    if args.vararg:
        rendered.append(
            "*" + _parameter(args.vararg.arg, args.vararg.annotation, None)
        )
    elif args.kwonlyargs:
        rendered.append("*")
    rendered.extend(
        _parameter(argument.arg, argument.annotation, default)
        for argument, default in zip(
            args.kwonlyargs,
            args.kw_defaults,
            strict=True,
        )
    )
    if args.kwarg:
        rendered.append(
            "**" + _parameter(args.kwarg.arg, args.kwarg.annotation, None)
        )
    return f"{public_name}({', '.join(rendered)})"


def _tool_nodes(tree: ast.Module) -> dict[str, ast.FunctionDef | ast.AsyncFunctionDef]:
    tools = {
        node.name: node
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and _is_tool(node)
    }
    imports: dict[str, tuple[str, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom) or node.module is None:
            continue
        for imported in node.names:
            imports[imported.asname or imported.name] = (node.module, imported.name)
    for node in tree.body:
        if (
            not isinstance(node, ast.Assign)
            or len(node.targets) != 1
            or not isinstance(node.targets[0], ast.Name)
            or not isinstance(node.value, ast.Call)
            or not isinstance(node.value.func, ast.Call)
            or not isinstance(node.value.func.func, ast.Attribute)
            or not isinstance(node.value.func.func.value, ast.Name)
            or node.value.func.func.value.id != "mcp"
            or node.value.func.func.attr != "tool"
            or len(node.value.args) != 1
            or not isinstance(node.value.args[0], ast.Name)
        ):
            continue
        imported = imports.get(node.value.args[0].id)
        if imported is None:
            continue
        module, function = imported
        module_path = ROOT / (module.replace(".", "/") + ".py")
        external_tree = ast.parse(module_path.read_text(encoding="utf-8"))
        external = next(
            candidate
            for candidate in external_tree.body
            if isinstance(candidate, (ast.FunctionDef, ast.AsyncFunctionDef))
            and candidate.name == function
        )
        tools[node.targets[0].id] = external
    return tools


def render() -> str:
    tree = ast.parse(SERVER.read_text(encoding="utf-8"))
    tools = _tool_nodes(tree)
    groups = [
        (name, TOOL_NAME.findall(raw_tools))
        for name, raw_tools in GROUP_ROW.findall(README.read_text(encoding="utf-8"))
    ]
    grouped = {tool for _, names in groups for tool in names}
    if grouped != set(tools):
        missing = sorted(set(tools) - grouped)
        unknown = sorted(grouped - set(tools))
        raise SystemExit(
            f"README groups differ from registered tools; missing={missing}, unknown={unknown}"
        )

    lines = [
        "# MCP Tool Reference",
        "",
        "Generated from `server.py` by `scripts/generate_tool_reference.py`.",
        "Do not edit this file manually.",
        "",
        "All tools return the common response envelope documented in the README.",
        "",
    ]
    for group, names in groups:
        lines.extend([
            f"## {group}",
            "",
            "| Tool | Signature | Description |",
            "|---|---|---|",
        ])
        for name in names:
            node = tools[name]
            first_paragraph = (ast.get_docstring(node) or "").split("\n\n", 1)[0]
            description = " ".join(first_paragraph.split())
            description = description.replace("|", "\\|")
            signature = html.escape(_signature(node, name), quote=False)
            lines.append(
                f"| `{name}` | <code>{signature}</code> | {description} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed reference differs from generated output",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(
                "docs/tool-reference.md is stale; run "
                "python scripts/generate_tool_reference.py"
            )
        print("tool reference is current")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
